version: "3.8"
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DBURL: dpg-ct0tekt6l47c73b9g800-a.oregon-postgres.render.com
      DBNAME: library_app_gdeb
      DBUSERNAME: library_app_gdeb_user
      DBPASSWORD: CBdr6f7ARfBliLyoz4W7f4uACRTpu7aG

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library-app
